# Generated by Django 6.0.7 on 2026-08-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='zaman', db_index=True)),
                ('metric', models.TextField(db_column='metrik')),
                ('resolution', models.TextField(db_column='coz')),
                ('vendor', models.TextField(db_column='vendor')),
                ('model_name', models.TextField(db_column='model_adi')),
                ('z_score', models.FloatField(db_column='z_skoru', null=True)),
                ('actual_value', models.FloatField(db_column='gercek_deger')),
                ('expected', models.FloatField(db_column='beklenen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anomali_sonuc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='zaman', db_index=True)),
                ('metric', models.TextField(db_column='metrik')),
                ('resolution', models.TextField(db_column='coz')),
                ('vendor', models.TextField(db_column='vendor')),
                ('model_name', models.TextField(db_column='model_adi')),
                ('forecast', models.FloatField(db_column='tahmin')),
                ('actual_value', models.FloatField(db_column='gercek', null=True)),
                ('horizon', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tahmin_sonuc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.TextField(db_column='metrik')),
                ('resolution', models.TextField(db_column='coz')),
                ('vendor', models.TextField(db_column='vendor')),
                ('wd', models.SmallIntegerField(db_column='wd')),
                ('tb', models.IntegerField(db_column='tb')),
                ('expected', models.FloatField(db_column='bek')),
                ('mad', models.FloatField(db_column='mad')),
            ],
            options={
                'db_table': 'egitim_profil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorid', models.TextField()),
                ('tpep_pickup_datetime', models.DateTimeField(db_index=True)),
                ('tpep_dropoff_datetime', models.DateTimeField()),
                ('passenger_count', models.BigIntegerField(null=True)),
                ('trip_distance', models.FloatField(null=True)),
                ('fare_amount', models.FloatField(null=True)),
                ('tip_amount', models.FloatField(null=True)),
                ('tolls_amount', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('pulocationid', models.BigIntegerField(null=True)),
                ('dolocationid', models.BigIntegerField(null=True)),
                ('sure_dk', models.FloatField(null=True)),
                ('hiz_mph', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'sefer_egitim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorid', models.TextField()),
                ('tpep_pickup_datetime', models.DateTimeField(db_index=True)),
                ('tpep_dropoff_datetime', models.DateTimeField()),
                ('passenger_count', models.BigIntegerField(null=True)),
                ('trip_distance', models.FloatField(null=True)),
                ('fare_amount', models.FloatField(null=True)),
                ('tip_amount', models.FloatField(null=True)),
                ('tolls_amount', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('pulocationid', models.BigIntegerField(null=True)),
                ('dolocationid', models.BigIntegerField(null=True)),
                ('sure_dk', models.FloatField(null=True)),
                ('hiz_mph', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'sefer_2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorid', models.TextField(blank=True, null=True)),
                ('tpep_pickup_datetime', models.DateTimeField(db_index=True)),
                ('tpep_dropoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('passenger_count', models.BigIntegerField(blank=True, null=True)),
                ('trip_distance', models.FloatField(blank=True, null=True)),
                ('fare_amount', models.FloatField(blank=True, null=True)),
                ('tip_amount', models.FloatField(blank=True, null=True)),
                ('tolls_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('pulocationid', models.BigIntegerField(blank=True, null=True)),
                ('dolocationid', models.BigIntegerField(blank=True, null=True)),
                ('sure_dk', models.FloatField(blank=True, null=True)),
                ('hiz_mph', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_entries', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_entry',
                'ordering': ['-added_at'],
            },
        ),
    ]
