# Generated by Django 6.0.7 on 2026-08-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traintrip',
            options={'managed': True},
        ),
    ]
