# Generated by Django 6.0.7 on 2026-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0002_alter_traintrip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='traintrip',
            name='hourly_avg_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='traintrip',
            name='hourly_trip_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traintrip',
            name='price_per_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='traintrip',
            name='trip_duration_minutes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='traintrip',
            name='trip_speed_mph',
            field=models.FloatField(null=True),
        ),
    ]
