# Generated by Django 6.0.7 on 2026-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0003_traintrip_hourly_avg_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualentry',
            name='hiz_mph',
        ),
        migrations.RemoveField(
            model_name='manualentry',
            name='sure_dk',
        ),
        migrations.RemoveField(
            model_name='manualentry',
            name='tpep_dropoff_datetime',
        ),
        migrations.RemoveField(
            model_name='traintrip',
            name='hiz_mph',
        ),
        migrations.RemoveField(
            model_name='traintrip',
            name='sure_dk',
        ),
        migrations.AddField(
            model_name='manualentry',
            name='hourly_avg_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='manualentry',
            name='hourly_trip_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manualentry',
            name='price_per_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='manualentry',
            name='trip_duration_minutes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='manualentry',
            name='trip_speed_mph',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='dolocationid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='fare_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='passenger_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='pulocationid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='tip_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='tolls_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='tpep_pickup_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='trip_distance',
            field=models.FloatField(null=True),
        ),
    ]
